backend:
  name: github
  repo: imperium-scents/imperium-scents.github.io # Nombre actual de tu repositorio
  branch: main

media_folder: "images"
public_folder: "/images"

collections:
  - name: "productos"
    label: "Mis Productos"
    folder: "productos"
    create: true
    fields:
      - {label: "Nombre", name: "title", widget: "string"}
      - {label: "Precio", name: "price", widget: "number"}
      - {label: "Imagen", name: "image", widget: "image"}
